### ISSUE TITLE
DOM: filter by tag

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#11]
1. Branch: feat/dom-filter
2. As a user, I should be able to filter recipes by a tag
3. I should be able to search recipes by their name
4. commit and PR

**Comment by JamieCaudill** [comment]
Make a function that pulls all the tags from all the recipes and puts them in an array. 
Eventually if you punch a tag into a search bar all the recipes with that tag should show up. 
For now maybe we have a dropdown list with all the tags to select from.
If there are common tags among lots of recipes maybe put them into a category.

**Comment by JamieCaudill** [comment]
Refactor the search functionality to search for every term in the search, tags, names.
split() might be good to use here

**Comment by Sulton88Mehron90** [comment]
const filterRecipes = (recipeData, filter) => {
  const recipes = [];
  const lowerCaseFilter = filter.toLowerCase();
  const searchTerms = lowerCaseFilter.split(' ');

  recipeData.forEach(recipe => {
    const lowerCaseRecipeName = recipe.name.toLowerCase();
    const recipeTags = recipe.tags.map(tag => tag.toLowerCase());

    const matchName = searchTerms.every(term => lowerCaseRecipeName.includes(term));
    const matchTag = searchTerms.every(term => recipeTags.includes(term));

    if ((matchName || matchTag) || filter === 'all') {
      recipes.push(recipe);
    }
  });

  if (recipes.length === 0) {
    return 'No results';
  }

  return recipes;
};

**Comment by Sulton88Mehron90** [comment]
// Test cases for refactored filterRecipes.
describe('filterRecipes', () => {
  it.only('should return recipes that match the search term in names or tags', () => {
    const searchTerm = 'chocolate chip';
    const filteredRecipes = filterRecipes(recipeData, searchTerm);
    expect(filteredRecipes).to.have.lengthOf(2);
    expect(filteredRecipes[0].name).to.equal('Loaded Chocolate Chip Pudding Cookie Cups');
  });

  it.only('should return recipes that match multiple search terms in names or tags', () => {
    const searchTerm = 'chocolate pudding';
    const filteredRecipes = filterRecipes(recipeData, searchTerm);
    expect(filteredRecipes).to.have.lengthOf(1);
    expect(filteredRecipes[0].name).to.equal('Loaded Chocolate Chip Pudding Cookie Cups');
  });

  it.only('should return all recipes when filter is set to "all"', () => {
    const filter = 'all';
    const filteredRecipes = filterRecipes(recipeData, filter);
    expect(filteredRecipes).to.have.lengthOf(50);
  });

  it.only('should return "No results" when no recipes match the search term', () => {
    const searchTerm = 'gnarwhale';
    const filteredRecipes = filterRecipes(recipeData, searchTerm);
    expect(filteredRecipes).to.equal('No results');
  });
});

**Comment by Sulton88Mehron90** [comment]
const filterRecipes = (recipeData, filter) => {
  const recipes = [];
  const lowerCaseFilter = filter.toLowerCase();
  console.log('parvin:', filter) 
  
  const searchTerms = lowerCaseFilter.split(' ');
  console.log('parvin', searchTerms)   
  
  recipeData.forEach(recipe => {
    const lowerCaseRecipeName = recipe.name.toLowerCase();
    const recipeTags = recipe.tags.map(tag => tag.toLowerCase());
    
    const matchName = searchTerms.some(term => lowerCaseRecipeName.includes(term));
   console.log('parvin:', matchName) 
    
    const matchTag = searchTerms.some(term => recipeTags.includes(term));
    console.log('parvin:', matchTag) 
    
    if ((matchName || matchTag) || filter === 'all') {
      recipes.push(recipe);
    }
    
  });
  if (recipes.length === 0) {
    return 'No results';
  }
  let uniqueRecipes = [... new Set(recipes)];
  return uniqueRecipes;
};
