### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#114]
- Check accessibility using both Lighthouse and WAVE
- If there are any issues, add them to the project board

**Comment by Sulton88Mehron90** [comment]
possible issue:
1. A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form. To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.

2. Headings: It is commendable that heading elements (h1, h2) are used to structure the content hierarchy we do! However, it is important to ensure that the heading levels are used appropriately and follow a logical order. I our html there is <div class="home__header2"> before the h1 tag. apparently it get the screen recorder confused even if its a class name.

3. using roles like button, search, or navigation appropriately can provide additional information to assistive technologies.
4. Form inputs: The search input fields have the required attribute, indicating that they must be filled in before submitting the form. This is helpful for form validation and informing users about mandatory fields.
 
6. Color contrast: It is important to ensure that the color contrast between the text and background meets accessibility standards. Without reviewing the actual colors used, it is difficult to assess the color contrast in the given code snippet.

**Comment by Sulton88Mehron90** [comment]
refactor: Edit to html tag tag to comply with accessibility, 
                Edit to css property to comply with accessibility
                Edit to alt tag to be more descriptive of the img  property to comply with accessibility
                Add aria-label to html button tag
                Check accessibility using both Lighthouse: 100% pass.
