### ISSUE TITLE
Refactor check: functions

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#120]
- Go through functions and check for:
   - DRY
   - SRP
- if a function can be refactored, add it to the project board

**Comment by Marisa5280** [comment]
Going to look over the code with my tutor tomorrow may 31, to figure out which functions need to be/could be refactored to be more DRY and SRP

**Comment by Marisa5280** [comment]
Still need to look at filterRecipes, recipe-ingredients, and recipeInstructions and the functions in dom updates. making good progress in making our code less smelly, more DRY and SRP
