### ISSUE TITLE
Pre-work: Iteration 5

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#124]
- Begin researching and pseudocoding how we are going to implement POST and the iteration 5 requirements.

**Comment by Marisa5280** [comment]
-update fetch GETs to use new api endpoints
  - users
  - recipes
  - ingredients


- Use POST to save recipes to local server
  - clone down local server from project spec link
  - follow set up instructions (cd to repo, npm install, npm start) in README
  - run local server in separate terminal window
```
fetch(url, {
  method: 'POST',
  body: JSON.stringify(someDataToSend) // our recipe to save
  headers: {
  	'Content-Type': 'application/json'
  }
})
  .then(response => response.json())
  .then(json => /*do something with json*/) // Add to saved recipes? not entirely sure
  .catch(err => /*do something with the error*/); // Alert user if POST request is unsuccessful 
```

**Comment by Marisa5280** [comment]
https://www.freecodecamp.org/news/how-to-make-api-calls-with-fetch/
