### ISSUE TITLE
Iteration 6: Usability Test Pre-work

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#132]
- Create a script for the usability test
- Decide what we are trying to learn from the test (can a user do ____? can a user find ____?
- Write step-by-step instructions for the participant.
- Prepare a few questions to ask the participant about how they felt while they were trying the feature.
- the usability test should not last for more than

**Comment by Marisa5280** [comment]
QUESTIONS
- can a user search for an ingredient, keyword, or tag and get resulting recipes?
- can a user save those recipes to their collection?
- can a user (after saving several recipes) search through their saved collection and return a filtered selection of recipes?
- can the user find any bugs? (correct answer: no!)
- is the page layout intuitive?

INSTRUCTIONS
1. using tuple, enable keyboard and mouse control
1. navigate to the recipe `recipe` 
1. save the recipe to your recipes
1. using the search bar search for cream and find the `creamsicle pie` recipe. save it.
1. On your own find a few more recipes and save them
1. Navigate to the User's saved recipes
1. using the saved recipes search bar search for `pie`
1. Go back into the `creamsicle pie` recipe and click on the print button to see the printer friendly page
1. Navigate back to the main page
1. on your own look around, can you find any bugs or things that could be better?
