### ISSUE TITLE
Function: filtered based on tag

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#3]
1. Make branch: feat/filter-tag
2. Write tests for a function that filters recipes based on tag.
3. Write function that passes tests.
4. Commit and PR.

**Comment by Marisa5280** [comment]
wrote pseudocode for function,
still need to pseudocode for tests

**Comment by Marisa5280** [comment]
wrote happy and sad tests pseudocode

**Comment by Marisa5280** [comment]
> // describe filterByTag function 
  // happy:
  // it should be a function
    // expect fiterByTag to be a function
  // it should return a subset array of the recipes with the filtered tag
    // expect filterByTag(recipeData, tag) to deep equal [array of tag recipes]
  // sad: 
  // it should return undefined if the tag does not exist
    // expect filterByTag(recipeData, nonexistantTag) to return "undefined"

**Comment by Marisa5280** [comment]
> // function filter by tag
  // we want to iterate through the recipes and return a subset of data that is fitered by the selected tag
  // .filter()
  // input: parameter of the recipesData (arr. of objects), and  the tag to filter
  // recipeData[index]["tags"] ("tags"?)
  // look at each recipe, if the recipe.tag === selectedTag filter to a selectTag array
  // output: return selectedTag array
