### ISSUE TITLE
Refactor filterByName function to use ES6

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#34]
```
function filterByName(recipeData, name) {
  var filteredRecipesByName = [];
  var lowerCaseName = name.toLowerCase()
  var lowerCaseRecipe;
    for(var i = 0; i < recipeData.length; i++) {
      lowerCaseRecipe = recipeData[i].name.toLowerCase()
      if(lowerCaseRecipe.includes(lowerCaseName)) {
        filteredRecipesByName.push(recipeData[i]);
      };
    };
  if (!filteredRecipesByName.length) {
    return 'No results';
  } 
  return filteredRecipesByName;
};
```
Refactor this function to use arrow syntax and iterators. No more for loops.

**Comment by Sulton88Mehron90** [comment]
const filterByName = (recipeData, name) => {
  const filteredRecipesByName = [];
  const lowerCaseName = name.toLowerCase();

  recipeData.forEach(recipe => {
    const lowerCaseRecipe = recipe.name.toLowerCase();
    if (lowerCaseRecipe.includes(lowerCaseName)) {
      filteredRecipesByName.push(recipe);
    }
  });

  if (!filteredRecipesByName.length) {
    return 'No results';
  }

  return filteredRecipesByName;
};

**Comment by Sulton88Mehron90** [comment]
//replaced forEach() with reduce()

const filterByName = (recipeData, name) => {
  const lowerCaseName = name.toLowerCase();

  const filteredRecipesByName = recipeData.reduce((filteredRecipes, recipe) => {
    const lowerCaseRecipe = recipe.name.toLowerCase();
    if (lowerCaseRecipe.includes(lowerCaseName)) {
      filteredRecipes.push(recipe);
    }
    return filteredRecipes;
  }, []);

  if (!filteredRecipesByName.length) {
    return 'No results';
  }

  return filteredRecipesByName;
};
