### ISSUE TITLE
Refactor recipeIngredients function

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#45]
Just see what you can do

**Comment by Sulton88Mehron90** [comment]
const recipeIngredients = (recipe) => {
  const filteredRecipe = recipeData.find(item => item.name === recipe);

  if (!filteredRecipe) {
    return `Sorry, cannot find a recipe for ${recipe}.`;
  }

  const ingredientIds = filteredRecipe.ingredients.map(ingredient => ingredient.id);

  const ingredientObjects = ingredientIds.map(ingredientId => {
    return ingredientsData.find(ingredient => ingredient.id === ingredientId);
  });

  const ingredientStrings = ingredientObjects.map(object => object.name);

  return ingredientStrings;
};
