### ISSUE TITLE
Function: directions

### ISSUE THREAD

**Issue by JamieCaudill** [JamieCaudill/whats-cookin-group-project#7]
1. Create branch: feat/directions
2. Write test for function that returns the directions/instructions for a given recipe
3. Write function to pass tests
4. commit and PR

**Comment by Sulton88Mehron90** [comment]
// function that returns the directions/instructions for a given recipe.
// input: parameter of the recipesData (arr. of objects)
// initialize `directions.innerHTML` as an empty string. 
//dynamically change info directions innerHTML for each element from an array 
  // directions.innerHTML = "";
// loop through each instruction in the recipe data using for loop or forEach()
// and getting `recipeData.instructions[i].instruction` and `instructionNumber = recipeData.instructions[i].number`
// concatenate the instruction and its number to the directions string
//output: return the concatenated directions

// function getRecipeInstructions(recipeData) {
//   let directions.innerHTML = "";
//   for (let i = 0; i < recipeData.instructions.length; i++) {
//     const instruction = recipeData.instructions[i].instruction;
//     const instructionNumber = recipeData.instructions[i].number;
//     directions += `${instructionNumber}. ${instruction}\n`;
//   };
//   return directions;
// };
// const recipeDirections = getRecipeInstructions(recipeSampleData[0]);
// console.log(recipeDirections);
